### ISSUE TITLE
Hackday 02172017

### ISSUE THREAD

**Issue by linan7788626** [linan7788626/hack_with_Matt#3]
@mpwiesner @jbkalmbach , hi guys, let's post stuff here.

we need the SEDs of the hosts and lenses. (six magnitudes)

**Comment by jbkalmbach** [comment]
[sprinkled_agn_230.txt](https://github.com/linan7788626/hack_with_Matt/files/784032/sprinkled_agn_230.txt)
[sprinkled_hosts_230.txt](https://github.com/linan7788626/hack_with_Matt/files/784033/sprinkled_hosts_230.txt)

**Comment by jbkalmbach** [comment]
These can be matched on the column "catsim_id".

**Comment by jbkalmbach** [comment]
[Updated version sprinkled_hosts_230.txt](https://github.com/linan7788626/hack_with_Matt/files/784053/sprinkled_hosts_230.txt)

**Comment by linan7788626** [comment]
@mpwiesner inputs for the lensing codes.

Lens: [xl1, xl2, vd, ql, phl, zd, twinkle_id]
[0.0, 0.0, 160.69409999999999, 0.90817660999999994, -150.98410000000001, 0.186, 24]

Host: [ysc1, ysc2, mag_tot, Reff, qs, phs, ndex, zs]
[-0.3190134, 0.087881310000000004, 19.283376799999999, 0.99138184766304205, 0.98021641259918724, 306.38729899999998, 4.0, 0.47999999999999998]

Lgal: [xc1, xc2, mag_tot, Reff_a, Reff_b, Theta, ndex, zl]
['53.0524882', '-27.7029739', '17.8301052', '1.6126157', '1.15325373', -150.98410000000001, 4.0, 0.186]

**Comment by jbkalmbach** [comment]
sims_sed_library is available here: https://lsst-web.ncsa.illinois.edu/sim-data/sed_library/seds_170124.tar.gz
