### ISSUE TITLE
Hack at U of B

### ISSUE THREAD

**Issue by linan7788626** [linan7788626/hack_with_Matt#5]
Hi @mpwiesner 

Let share data and discuss here.

Best,
Nan Li

**Comment by mpwiesner** [comment]
# parameters of the mass model of the lens
#
xl1      # x position of the lens, arcsecond
xl2      # y position of the source, arcsecond
vd       # velocity dispersion, km/s
ql       # b/a
phl      # orientation of the lens,  degree
zl       # lens redshift

# parameters of the host galaxy of lensed point source
#
ysc1     # projected postion of the source, arcsecond
ysc2     # projected postion of the source, arcsecnd
mags     # magnitude of the source
Reff     # Effective radius of Sersic Profile of the source, arcsecnd
qs       # b/a of the source
phs      # orientation of the source, degree
ns       # index of the Sersic Profile of the source
zs       # redshift of the source
#INPUT BELOW HERE
x1 y1 vd ql phl  zl    ysc1 ysc2 mags     Reff qs    phs  ns zs
0.0 0.0 160.69409999999999 0.90817660999999994 -150.98410000000001 0.184 -0.3190134 0.087881310000000004 19.283376799999999 0.99138184766304205 0.98021641259918724 306.38729899999998 4.0 0.47999999999999998
0.0 0.0 260.69409999999999 0.90817660999999994 -250.98410000000001 0.184 -0.3190134 0.087881310000000004 19.283376799999999 0.99138184766304205 0.98021641259918724 306.38729899999998 5.0 0.47999999999999998

**Comment by linan7788626** [comment]
@mpwiesner 
The code for compressing fits files in python.

```python
import pyfits
import subprocess as sp

filename = "/the/path/to/your/file.fits"
pyfits.writeto(filename, data, overwrite=True)
cmd = "gzip -f " + filename
sp.call(cmd, shell=True)
```
